'use client'

import { useEffect, useState } from 'react'
import { ArrowUpRight, Camera, ChevronDown, Globe2, MapPin, Menu, MessageCircle, MoveRight, Sparkles, X } from 'lucide-react'
import { Button } from '@/components/ui/button'

type Retreat = {
  id: string
  slug: string
  title: string
  destination: string
  date: string
  nights: number
  accommodation: string
  transportation: string
  price: string
  availableSpots: string
  description: string
  included: string[]
  notIncluded: string[]
  image: string
}

type GalleryImage = { id: string; title: string; category: string; image: string }

// Edit future retreats, partners, gallery items and contact links in this central configuration area.
const siteConfig = {
  brand: 'Solo Retreats',
  tagline: 'Small-group retreats and travel experiences across Egypt.',
  contact: {
    whatsappNumber: '[replace-with-number]',
    email: '[replace-with-email]',
    facebook: '#placeholder-facebook',
    instagram: '#placeholder-instagram',
  },
}

const socialLinks = {
  facebook: siteConfig.contact.facebook,
  instagram: siteConfig.contact.instagram,
  whatsapp: `https://wa.me/${siteConfig.contact.whatsappNumber}`,
}

function whatsappLink(retreat = 'a retreat', name = '') {
  const message = `Hello Solo Retreats, I am interested in booking the ${retreat}. My name is ${name || '[your name]'}.`
  return `${socialLinks.whatsapp}?text=${encodeURIComponent(message)}`
}

const retreats: Retreat[] = [
  { id: 'nuweiba-escape', slug: 'nuweiba-escape', title: 'Nuweiba Escape', destination: 'Nuweiba, Egypt', date: '[Add dates]', nights: 2, accommodation: 'Partner camp', transportation: 'Independent bus partner', price: 'Starting from [price]', availableSpots: '[Number] spots', description: 'A slow, sun-warmed escape to the Red Sea coast with room for sea air, good conversation and a proper pause.', included: ['Planned itinerary', 'Accommodation coordination', 'Arranged transportation'], notIncluded: ['Personal expenses', 'Meals not mentioned', 'Anything not in final details'], image: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=1200&q=85' },
  { id: 'siwa-reset', slug: 'siwa-reset', title: 'Siwa Reset', destination: 'Siwa Oasis, Egypt', date: '[Placeholder date]', nights: 3, accommodation: 'Independent local camp', transportation: 'Independent transportation partner', price: 'Starting from [price]', availableSpots: '[Number] spots', description: 'A gentle oasis retreat built around quiet mornings, natural landscapes and unhurried evenings.', included: ['Curated itinerary', 'Accommodation coordination', 'Transportation coordination'], notIncluded: ['Personal purchases', 'Unlisted meals', 'Optional activities'], image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=85' },
  { id: 'dahab-weekend', slug: 'dahab-weekend', title: 'Dahab Weekend', destination: 'Dahab, Egypt', date: '[Placeholder date]', nights: 2, accommodation: 'Independent partner stay', transportation: 'Independent bus partner', price: 'Starting from [price]', availableSpots: '[Number] spots', description: 'A compact coastal reset for anyone who wants to trade routine for salt water and open skies.', included: ['Group planning', 'Stay coordination', 'Transportation coordination'], notIncluded: ['Personal expenses', 'Meals not mentioned', 'Unconfirmed extras'], image: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85' },
]

const steps = [['01', 'Choose Your Retreat', 'Browse upcoming trips.'], ['02', 'Check the Details', 'Review the destination, stay, transport, dates and price.'], ['03', 'Reserve Your Spot', 'Contact Solo Retreats or submit your booking request.'], ['04', 'Pack Your Bag', 'We handle the planning. You enjoy the experience.']]
const features = [['Small Groups', 'More personal and comfortable experiences.'], ['Carefully Selected Places', 'We work with places that fit the experience we want to create.'], ['Reliable Transportation', 'Transportation is arranged through independent partners.'], ['Real Experiences', 'The goal is not just checking a destination off your list.'], ['Personal Presence', 'The organizer is part of the experience.'], ['Simple and Transparent', 'Clear pricing and clear information before you book.']]
const faqs = [
  ['What is included in the retreat price?', 'The final retreat details will list what is included, such as planned activities, accommodation coordination and arranged transportation.'],
  ['What is not included?', 'Personal expenses, meals not specifically mentioned, optional activities and anything not listed in the final retreat details are not included.'],
  ['How do I reserve my spot?', 'Send Solo Retreats a message using the contact details below. We will share current availability and booking steps.'],
  ['Is transportation included?', 'Transportation may be included depending on the retreat. The retreat card and final details will make this clear.'],
  ['Where does the transportation depart from?', 'Departure details are shared with confirmed travelers before the retreat.'],
  ['What type of accommodation is provided?', 'Accommodation is arranged with independent local partners. The specific camp or stay is listed for each retreat.'],
  ['Can I come alone?', 'Yes. The retreats are designed to feel welcoming whether you arrive alone or with someone you know.'],
  ['Are couples and friends welcome?', 'Yes. Couples and friends are welcome, while the experience remains open to solo travelers too.'],
  ['What happens if I need to cancel?', 'Cancellation terms will be shared clearly before you reserve. Please contact Solo Retreats for the current policy.'],
  ['Is the trip suitable for first-time travelers?', 'Yes. The experience is planned to be approachable, with clear information shared before departure.'],
  ['Who organizes the trip?', 'Solo Retreats organizes and curates the retreat experience and personally joins the trips.'],
  ['Are the camp and transportation owned by Solo Retreats?', 'No. Solo Retreats is the organizer and curator of the retreat experience. Accommodation and transportation are provided by independent partners.'],
]
const gallery: GalleryImage[] = [
  ['destination-coast', 'Red Sea coast', 'Destination', 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=900&q=85'],
  ['camp-evening', 'Camp evening', 'Camp', 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=900&q=85'],
  ['desert-light', 'Desert light', 'Nature', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=85'],
  ['road-trip', 'On the road', 'Transportation', 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=900&q=85'],
  ['shared-moment', 'Shared moments', 'People', 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=85'],
  ['morning-walk', 'Morning walk', 'Activities', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85'],
  ['camp-table', 'A table outside', 'Food', 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85'],
  ['night-sky', 'Under the night sky', 'Sunset and Night', 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=85'],
].map(([id, title, category, image]) => ({ id, title, category, image }))

export function RetreatsLanding() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [openFaq, setOpenFaq] = useState<number | null>(null)
  const [selectedRetreat, setSelectedRetreat] = useState<Retreat | null>(null)
  const [selectedImage, setSelectedImage] = useState<GalleryImage | null>(null)
  const [bookingRetreat, setBookingRetreat] = useState<Retreat | null>(null)
  useEffect(() => { document.body.style.overflow = selectedRetreat || selectedImage ? 'hidden' : ''; return () => { document.body.style.overflow = '' } }, [selectedRetreat, selectedImage])
  useEffect(() => { const close = (event: KeyboardEvent) => event.key === 'Escape' && (setSelectedRetreat(null), setSelectedImage(null)); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [])

  return (
    <main className="min-h-screen overflow-x-hidden bg-[#f6f3ed] text-[#24332d]">
      <nav className="fixed inset-x-0 top-0 z-50 border-b border-white/20 bg-[#f6f3ed]/85 backdrop-blur-md" aria-label="Main navigation"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-10"><a href="#home" className="flex items-center gap-3" onClick={() => setMenuOpen(false)}><span className="flex size-9 items-center justify-center rounded-full bg-[#26473d] font-serif text-lg font-semibold text-[#f6f3ed]" aria-label="Solo Retreats logo">S</span><span className="font-serif text-xl tracking-tight">Solo Retreats</span></a><div className="hidden items-center gap-7 text-sm text-[#5c6a63] lg:flex">{['Retreats', 'About', 'Partners', 'Gallery', 'FAQ', 'Contact'].map((item) => <a key={item} href={`#${item.toLowerCase()}`} className="transition-colors hover:text-[#26473d]">{item}</a>)}<Button asChild className="rounded-full bg-[#26473d] px-5 text-[#f6f3ed] hover:bg-[#1d3931]"><a href="#retreats">Explore Retreats <ArrowUpRight data-icon="inline-end" /></a></Button></div><button className="rounded-full p-2 lg:hidden" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <div className="border-t border-[#24332d]/10 bg-[#f6f3ed] px-5 pb-6 pt-4 lg:hidden"><div className="flex flex-col gap-1">{['Home', 'Retreats', 'About', 'Partners', 'Gallery', 'FAQ', 'Contact'].map((item) => <a key={item} href={item === 'Home' ? '#home' : `#${item.toLowerCase()}`} onClick={() => setMenuOpen(false)} className="min-h-12 rounded-xl px-3 py-3 text-lg hover:bg-[#e9e6df]">{item}</a>)}<Button asChild className="mt-3 min-h-12 rounded-full bg-[#26473d] text-[#f6f3ed] hover:bg-[#1d3931]"><a href="#retreats" onClick={() => setMenuOpen(false)}>Explore Retreats <ArrowUpRight data-icon="inline-end" /></a></Button></div></div>}</nav>

      <section id="home" className="relative flex min-h-[620px] items-end overflow-hidden px-5 pb-28 pt-28 sm:min-h-[680px] sm:pb-16 lg:min-h-[850px] lg:px-10 lg:pb-20"><div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: `url(${retreats[0].image})` }} role="img" aria-label="Rocky desert coast at sunset in Egypt" /><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(18,34,29,.12),rgba(18,34,29,.82))]" /><div className="relative mx-auto w-full max-w-7xl text-[#faf8f2]"><div className="mb-8 flex items-center gap-3 text-xs uppercase tracking-[.24em] text-[#e8dfce]"><span className="size-2 rounded-full bg-[#d69c55]" /> Curated escapes across Egypt</div><h1 className="max-w-[11ch] font-serif text-[clamp(2.75rem,12vw,4.5rem)] leading-[.98] tracking-[-.04em] sm:max-w-4xl sm:text-8xl lg:text-[9rem]">Your next<br /><em className="font-light">escape</em> starts here.</h1><div className="mt-10 flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><p className="max-w-md text-lg leading-relaxed text-[#eee8dc]">Small-group retreats, beautiful places and carefully planned experiences across Egypt.</p><div className="flex w-full flex-col gap-3 sm:w-auto sm:flex-row"><Button asChild className="min-h-12 w-full rounded-full bg-[#d69c55] px-6 text-[#24332d] hover:bg-[#e4b477] sm:w-auto"><a href="#retreats">Explore Our Retreats <MoveRight data-icon="inline-end" /></a></Button><Button asChild variant="outline" className="rounded-full border-white/50 bg-white/10 px-6 text-white hover:bg-white/20 hover:text-white"><a href="#contact">Contact Us</a></Button></div></div><p className="mt-14 text-xs uppercase tracking-[.18em] text-[#d6d0c4]">Curated by Solo Retreats <span className="mx-2 text-[#d69c55]">|</span> Hosted with independent local partners</p></div></section>

      <section id="retreats" className="mx-auto max-w-7xl px-5 py-24 lg:px-10 lg:py-36"><SectionIntro eyebrow="Upcoming retreats" title={<>Find your next<br /><em className="font-light">kind of away.</em></>} copy="Placeholder retreat information is clearly marked and can be replaced from one structured data list as plans are confirmed." /><div className="grid gap-6 lg:grid-cols-3">{retreats.map((retreat) => <article key={retreat.id} className="group overflow-hidden rounded-[1.6rem] bg-[#e7e1d5]"><div className="h-64 bg-cover bg-center transition-transform duration-500 group-hover:scale-105" style={{ backgroundImage: `url(${retreat.image})` }} role="img" aria-label={`${retreat.title} placeholder image`} /><div className="relative bg-[#e7e1d5] p-6"><span className="rounded-full bg-[#d69c55]/20 px-3 py-1 text-[10px] font-semibold uppercase tracking-[.15em] text-[#9a5f2d]">Placeholder details</span><p className="mt-5 flex items-center gap-2 text-sm text-[#68746d]"><MapPin size={15} /> {retreat.destination}</p><h3 className="mt-2 font-serif text-3xl">{retreat.title}</h3><p className="mt-3 text-sm leading-relaxed text-[#68746d]">{retreat.description}</p><div className="mt-6 grid grid-cols-2 gap-4 border-y border-[#24332d]/15 py-5 text-xs"><Info label="Date" value={retreat.date} /><Info label="Nights" value={`${retreat.nights} nights`} /><Info label="Accommodation" value={retreat.accommodation} /><Info label="Transport" value={retreat.transportation} /><Info label="From" value={retreat.price} /><Info label="Spots" value={retreat.availableSpots} /></div><Button className="mt-6 w-full rounded-full bg-[#26473d] text-[#f6f3ed] hover:bg-[#1d3931]" onClick={() => { setSelectedRetreat(retreat); setBookingRetreat(retreat) }}>View Retreat <ArrowUpRight data-icon="inline-end" /></Button></div></article>)}</div></section>

      <section className="bg-[#26473d] px-5 py-24 text-[#f6f3ed] lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.2em] text-[#d69c55]">Keep it simple</p><h2 className="font-serif text-5xl leading-none sm:text-6xl">How it<br /><em className="font-light">works.</em></h2></div><div className="grid gap-0 sm:grid-cols-2">{steps.map(([number, title, copy]) => <div key={number} className="border-t border-white/20 py-7 sm:px-6 first:sm:pl-0"><span className="text-sm text-[#d69c55]">{number}</span><h3 className="mt-8 font-serif text-2xl">{title}</h3><p className="mt-2 max-w-xs text-sm leading-relaxed text-[#c9d0c9]">{copy}</p></div>)}</div></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-24 lg:px-10 lg:py-36"><div className="mb-12 max-w-xl"><p className="mb-4 text-xs font-semibold uppercase tracking-[.2em] text-[#b6783c]">Why come with us</p><h2 className="font-serif text-5xl leading-none tracking-tight sm:text-6xl">The details make<br /><em className="font-light">the difference.</em></h2></div><div className="grid gap-px overflow-hidden rounded-3xl border border-[#24332d]/10 bg-[#24332d]/10 sm:grid-cols-2 lg:grid-cols-3">{features.map(([title, copy], index) => <div key={title} className="bg-[#f6f3ed] p-7 transition-colors hover:bg-[#e9e6df]"><span className="flex size-10 items-center justify-center rounded-full bg-[#d69c55]/20 text-sm text-[#9a5f2d]">{String(index + 1).padStart(2, '0')}</span><h3 className="mt-12 font-serif text-2xl">{title}</h3><p className="mt-3 text-sm leading-relaxed text-[#68746d]">{copy}</p></div>)}</div></section>

      <section id="about" className="bg-[#e7e1d5] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><div className="min-h-[460px] rounded-[2rem] bg-cover bg-center" style={{ backgroundImage: `url(${gallery[5].image})` }} role="img" aria-label="Traveler looking across a quiet landscape" /><div className="lg:pl-10"><p className="mb-4 text-xs font-semibold uppercase tracking-[.2em] text-[#b6783c]">A personal invitation</p><h2 className="font-serif text-5xl leading-none sm:text-6xl">Meet the person<br />behind <em className="font-light">Solo Retreats.</em></h2><div className="mt-8 flex flex-col gap-4 text-base leading-relaxed text-[#68746d]"><p>Solo Retreats started from a simple idea: travel does not always have to be complicated, expensive or crowded.</p><p>The person behind each trip believes the best escapes leave space for quiet, good conversation and the unexpected. That is why every experience is kept small, personal and thoughtfully planned.</p><p>The organizer personally joins the trips, stays close to the details and chooses honest partnerships over one-size-fits-all packages.</p></div><Button asChild variant="outline" className="mt-8 rounded-full border-[#26473d] text-[#26473d] hover:bg-[#26473d] hover:text-[#f6f3ed]"><a href={socialLinks.instagram}>Follow the journey <ArrowUpRight data-icon="inline-end" /></a></Button></div></div></section>

      <section id="partners" className="bg-[#f6f3ed] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="Our Partners" title={<>Good places are<br /><em className="font-light">made together.</em></>} copy="We work with carefully selected local partners to make every retreat comfortable, safe and enjoyable. Solo Retreats curates the experience while our partners provide accommodation and transportation services." /><div className="grid gap-6 lg:grid-cols-2"><PartnerCard title="Lily Camp" label="Independent accommodation partner" description="A placeholder profile for the local camp that may host selected retreats. Confirmed camp details will be added here." details={['Camp name: Lily Camp', 'Location: [Placeholder location]', 'Gallery: [Placeholder images]']} cta="Explore Lily Camp" disclaimer="Lily Camp is an independent accommodation partner and is not owned by Solo Retreats." /><PartnerCard title="Cairo VIP Bus" label="Independent transportation partner" description="A placeholder profile for a transportation provider. Confirmed vehicle and service details will be added here." details={['Type: [Placeholder transportation type]', 'Passengers can expect: [Placeholder details]', 'Contact: [Placeholder contact information]']} cta="Explore Transportation Partner" disclaimer="Cairo VIP Bus is an independent transportation partner and is not owned by Solo Retreats." /></div></div></section>

      <section id="gallery" className="bg-[#e7e1d5] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="Gallery" title={<>A preview of<br /><em className="font-light">the feeling.</em></>} copy="Image placeholders are organized by category so they can be replaced with real retreat photography later." /><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{gallery.map((item, index) => <button key={item.id} className={`group relative min-h-[170px] overflow-hidden rounded-2xl text-left sm:min-h-[200px] ${index === 0 || index === 7 ? 'md:row-span-2 md:min-h-[420px]' : ''}`} onClick={() => setSelectedImage(item)} aria-label={`Open ${item.title} image`}><div className="absolute inset-0 bg-cover bg-center transition-transform duration-500 group-hover:scale-105" style={{ backgroundImage: `url(${item.image})` }} /><div className="absolute inset-0 bg-gradient-to-t from-[#172c25]/80 via-transparent to-transparent" /><div className="relative flex h-full min-h-[200px] flex-col justify-end p-4 text-white"><span className="text-[10px] uppercase tracking-[.16em] text-[#e9c18e]">{item.category}</span><span className="mt-1 font-serif text-xl">{item.title}</span></div></button>)}</div></div></section>

      <section id="faq" className="mx-auto max-w-4xl px-5 py-24 lg:py-32"><div className="mb-12 text-center"><p className="mb-4 text-xs font-semibold uppercase tracking-[.2em] text-[#b6783c]">Good to know</p><h2 className="font-serif text-5xl tracking-tight">Questions, answered.</h2></div><div className="border-t border-[#24332d]/15">{faqs.map(([question, answer], index) => <div key={question} className="border-b border-[#24332d]/15"><button className="flex w-full items-center justify-between gap-6 py-6 text-left font-serif text-xl" onClick={() => setOpenFaq(openFaq === index ? null : index)} aria-expanded={openFaq === index} aria-controls={`faq-answer-${index}`}>{question}<ChevronDown aria-hidden="true" className={`shrink-0 transition-transform ${openFaq === index ? 'rotate-180' : ''}`} /></button>{openFaq === index && <p id={`faq-answer-${index}`} className="max-w-2xl pb-6 text-sm leading-relaxed text-[#68746d]">{answer}</p>}</div>)}</div></section>

      <section id="contact" className="mx-5 mb-20 overflow-hidden rounded-[2rem] bg-[#d69c55] px-6 py-20 text-center sm:px-10 lg:mx-10 lg:py-28"><Sparkles className="mx-auto mb-6 text-[#26473d]" /><h2 className="font-serif text-5xl leading-none tracking-tight text-[#24332d] sm:text-7xl">Ready to escape<br /><em className="font-light">the routine?</em></h2><p className="mx-auto mt-6 max-w-md text-base text-[#4f4a3d]">Choose your next retreat and come with us.</p><div className="mt-9 flex flex-col items-stretch justify-center gap-3 sm:flex-row sm:items-center"><Button className="rounded-full bg-[#26473d] px-6 text-[#f6f3ed] hover:bg-[#1d3931]" onClick={() => document.getElementById('booking-form')?.scrollIntoView({ behavior: 'smooth' })}>Book Your Spot <ArrowUpRight data-icon="inline-end" /></Button><Button asChild variant="outline" className="rounded-full border-[#26473d] text-[#26473d] hover:bg-[#26473d] hover:text-[#f6f3ed]"><a href={whatsappLink()} target="_blank" rel="noreferrer"><MessageCircle data-icon="inline-start" /> WhatsApp Us</a></Button></div><p className="mt-8 text-xs text-[#6e563c]">Contact details are placeholders until the business confirms its official channels.</p></section><BookingForm key={bookingRetreat?.id ?? 'booking'} initialRetreat={bookingRetreat} />
      <section className="sr-only" aria-label="Trust statement"><p>Solo Retreats organizes small-group experiences with independent local accommodation and transportation partners.</p></section><div className="fixed inset-x-0 bottom-0 z-40 border-t border-[#24332d]/10 bg-[#f6f3ed]/95 p-3 pb-[calc(.75rem+env(safe-area-inset-bottom))] shadow-[0_-8px_24px_rgba(36,51,45,.12)] backdrop-blur-md lg:hidden"><a href={whatsappLink()} target="_blank" rel="noreferrer" className="flex min-h-12 w-full items-center justify-center gap-2 rounded-full bg-[#26473d] px-4 text-sm font-semibold text-[#f6f3ed] shadow-sm"><MessageCircle aria-hidden="true" /> Reserve Your Spot</a></div>
      <section className="border-t border-[#24332d]/10 px-5 py-20 lg:px-10"><div className="mx-auto max-w-7xl text-center"><p className="mb-4 text-xs font-semibold uppercase tracking-[.2em] text-[#b6783c]">Stay close to the next escape</p><h2 className="font-serif text-5xl tracking-tight">Follow Solo Retreats</h2><p className="mx-auto mt-5 max-w-md text-sm leading-relaxed text-[#68746d]">New trips, real moments and upcoming retreats on our social pages.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><SocialLink href={socialLinks.facebook} label="Facebook" icon={<Globe2 data-icon="inline-start" aria-hidden="true" />} /><SocialLink href={socialLinks.instagram} label="Instagram" icon={<Camera data-icon="inline-start" aria-hidden="true" />} /><SocialLink href={socialLinks.whatsapp} label="WhatsApp" icon={<MessageCircle data-icon="inline-start" aria-hidden="true" />} /></div></div></section>
      <footer className="border-t border-[#24332d]/10 px-5 py-12 lg:px-10"><div className="mx-auto grid max-w-7xl gap-10 sm:grid-cols-2 lg:grid-cols-[1.5fr_1fr_1fr]"><div><a href="#home" className="font-serif text-2xl">Solo Retreats</a><p className="mt-4 max-w-xs text-sm leading-relaxed text-[#68746d]">Small-group retreats and travel experiences across Egypt.</p></div><div className="grid grid-cols-2 gap-3 text-sm text-[#68746d]"><a href="#retreats">Retreats</a><a href="#about">About</a><a href="#partners">Partners</a><a href="#gallery">Gallery</a><a href="#faq">FAQ</a><a href="#contact">Contact</a></div><div className="flex items-start gap-3"><SocialLink href={socialLinks.instagram} label="Instagram" icon={<Camera aria-hidden="true" />} /><SocialLink href={socialLinks.facebook} label="Facebook" icon={<Globe2 aria-hidden="true" />} /><SocialLink href={socialLinks.whatsapp} label="WhatsApp" icon={<MessageCircle aria-hidden="true" />} /></div></div><div className="mx-auto mt-12 max-w-7xl border-t border-[#24332d]/10 pt-6 text-xs leading-relaxed text-[#68746d]">Solo Retreats organizes and curates travel experiences in cooperation with independent accommodation and transportation partners.</div></footer>

      {selectedRetreat && <Modal title={selectedRetreat.title} onClose={() => setSelectedRetreat(null)}><div className="grid gap-6 sm:grid-cols-[.8fr_1.2fr]"><div className="min-h-56 rounded-2xl bg-cover bg-center" style={{ backgroundImage: `url(${selectedRetreat.image})` }} role="img" aria-label={`${selectedRetreat.title} placeholder image`} /><div><p className="text-sm text-[#68746d]">{selectedRetreat.destination} · {selectedRetreat.date}</p><p className="mt-4 leading-relaxed text-[#68746d]">{selectedRetreat.description}</p><div className="mt-5 grid grid-cols-2 gap-4 text-sm"><Info label="Included" value={selectedRetreat.included.join(', ')} /><Info label="Not included" value={selectedRetreat.notIncluded.join(', ')} /></div><Button asChild className="mt-6 rounded-full bg-[#26473d] text-[#f6f3ed] hover:bg-[#1d3931]"><a href="#contact" onClick={() => setSelectedRetreat(null)}>Ask about this retreat <ArrowUpRight data-icon="inline-end" /></a></Button></div></div></Modal>}
      {selectedImage && <Modal title={selectedImage.title} onClose={() => setSelectedImage(null)}><div className="aspect-video rounded-2xl bg-cover bg-center" style={{ backgroundImage: `url(${selectedImage.image})` }} role="img" aria-label={`${selectedImage.title} placeholder image`} /><p className="mt-4 text-sm uppercase tracking-[.16em] text-[#b6783c]">{selectedImage.category} · Placeholder image</p></Modal>}
    </main>
  )
}

function BookingForm({ initialRetreat }: { initialRetreat: Retreat | null }) {
  const [submitted, setSubmitted] = useState(false)
  const [retreatId, setRetreatId] = useState(initialRetreat?.id ?? retreats[0].id)
  const [error, setError] = useState('')
  const [name, setName] = useState('')

  function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const form = new FormData(event.currentTarget)
    if (!name.trim() || !String(form.get('phone') || '').trim() || !String(form.get('guests') || '').trim()) {
      setError('Please add your name, phone number and number of guests.')
      return
    }
    setError('')
    setSubmitted(true)
    // TODO: Replace this client-only confirmation with a POST to the booking API.
  }

  if (submitted) return <section id="booking-form" className="mx-auto max-w-3xl px-5 py-20 text-center lg:py-28"><div className="rounded-[2rem] bg-[#e7e1d5] p-10"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#b6783c]">Request received</p><h2 className="mt-4 font-serif text-4xl">Thank you, {name}.</h2><p className="mx-auto mt-4 max-w-md text-sm leading-relaxed text-[#68746d]">This is a demo confirmation. We will connect this form to a booking endpoint once one is configured.</p><Button className="mt-7 rounded-full bg-[#26473d] text-[#f6f3ed] hover:bg-[#1d3931]" onClick={() => setSubmitted(false)}>Send another request</Button></div></section>

  return <section id="booking-form" className="mx-auto max-w-5xl px-5 py-20 lg:px-10 lg:py-28"><div className="grid gap-10 rounded-[2rem] bg-[#e7e1d5] p-6 sm:p-10 lg:grid-cols-[.8fr_1.2fr] lg:p-14"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#b6783c]">Start a conversation</p><h2 className="mt-4 font-serif text-5xl leading-none">Reserve your<br /><em className="font-light">escape.</em></h2><p className="mt-6 text-sm leading-relaxed text-[#68746d]">Tell us what you are interested in and we will share the current details before anything is confirmed.</p></div><form className="flex flex-col gap-4" onSubmit={handleSubmit} noValidate>{error && <p role="alert" className="rounded-xl bg-red-950/10 px-4 py-3 text-sm text-red-950">{error}</p>}<label className="flex flex-col gap-2 text-sm">Full name<input required value={name} onChange={(event) => setName(event.target.value)} className="rounded-xl border border-[#24332d]/15 bg-[#f6f3ed] px-4 py-3 outline-none focus:ring-2 focus:ring-[#b6783c]" /></label><label className="flex flex-col gap-2 text-sm">Phone number<input required name="phone" type="tel" className="rounded-xl border border-[#24332d]/15 bg-[#f6f3ed] px-4 py-3 outline-none focus:ring-2 focus:ring-[#b6783c]" /></label><label className="flex flex-col gap-2 text-sm">Selected retreat<select name="retreat" value={retreatId} onChange={(event) => setRetreatId(event.target.value)} className="rounded-xl border border-[#24332d]/15 bg-[#f6f3ed] px-4 py-3 outline-none focus:ring-2 focus:ring-[#b6783c]">{retreats.map((retreat) => <option key={retreat.id} value={retreat.id}>{retreat.title}</option>)}</select></label><label className="flex flex-col gap-2 text-sm">Number of guests<input required name="guests" type="number" min="1" max="20" className="rounded-xl border border-[#24332d]/15 bg-[#f6f3ed] px-4 py-3 outline-none focus:ring-2 focus:ring-[#b6783c]" /></label><label className="flex flex-col gap-2 text-sm">Message<textarea name="message" rows={4} className="resize-none rounded-xl border border-[#24332d]/15 bg-[#f6f3ed] px-4 py-3 outline-none focus:ring-2 focus:ring-[#b6783c]" placeholder="Anything you would like us to know?" /></label><Button type="submit" className="rounded-full bg-[#26473d] text-[#f6f3ed] hover:bg-[#1d3931]">Submit booking request</Button></form></div></section>
}

function SectionIntro({ eyebrow, title, copy }: { eyebrow: string; title: React.ReactNode; copy: string }) { return <div className="mb-12 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.2em] text-[#b6783c]">{eyebrow}</p><h2 className="max-w-xl font-serif text-5xl leading-none tracking-tight sm:text-6xl">{title}</h2></div><p className="max-w-md text-sm leading-relaxed text-[#68746d]">{copy}</p></div> }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="mb-1 text-[10px] uppercase tracking-wider text-[#68746d]">{label}</p><p className="text-sm leading-snug text-[#24332d]">{value}</p></div> }
function PartnerCard({ title, label, description, details, cta, disclaimer }: { title: string; label: string; description: string; details: string[]; cta: string; disclaimer: string }) { return <article className="rounded-[1.6rem] bg-[#e7e1d5] p-7 sm:p-9"><span className="text-xs font-semibold uppercase tracking-[.17em] text-[#b6783c]">{label}</span><div className="mt-7 flex min-h-36 items-center justify-center rounded-2xl border border-dashed border-[#24332d]/20 bg-[#f6f3ed]/50 text-center text-sm text-[#68746d]">Image gallery placeholder</div><h3 className="mt-7 font-serif text-4xl">{title}</h3><p className="mt-3 text-sm leading-relaxed text-[#68746d]">{description}</p><div className="mt-6 flex flex-col gap-2 text-sm text-[#68746d]">{details.map((detail) => <p key={detail}>{detail}</p>)}</div><div className="mt-7 flex flex-wrap gap-2 text-xs"><a href="#placeholder-facebook" className="rounded-full border border-[#24332d]/15 px-3 py-2">Facebook placeholder</a><a href="#placeholder-instagram" className="rounded-full border border-[#24332d]/15 px-3 py-2">Instagram placeholder</a><a href="#placeholder-maps" className="rounded-full border border-[#24332d]/15 px-3 py-2">Google Maps placeholder</a></div><Button variant="outline" className="mt-7 rounded-full border-[#26473d] text-[#26473d] hover:bg-[#26473d] hover:text-[#f6f3ed]">{cta} <ArrowUpRight data-icon="inline-end" /></Button><p className="mt-6 text-xs leading-relaxed text-[#68746d]">{disclaimer}</p></article> }
function SocialLink({ href, label, icon }: { href: string; label: string; icon?: React.ReactNode }) { return <a href={href} aria-label={label} target={href.startsWith('http') ? '_blank' : undefined} rel={href.startsWith('http') ? 'noreferrer' : undefined} className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#24332d]/20 px-5 py-3 text-sm transition-colors hover:bg-[#e9e6df]"><span className="flex size-4 items-center justify-center" aria-hidden="true">{icon}</span>{label}</a> }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-[#172c25]/70 p-5" role="presentation" onClick={onClose}><div role="dialog" aria-modal="true" aria-label={title} className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-[1.6rem] bg-[#f6f3ed] p-6 sm:p-9" onClick={(event) => event.stopPropagation()}><div className="mb-7 flex items-start justify-between gap-4"><h2 className="font-serif text-4xl">{title}</h2><button onClick={onClose} aria-label="Close dialog" className="rounded-full p-2 hover:bg-[#e9e6df]"><X /></button></div>{children}</div></div> }

export default RetreatsLanding
